FROM mukerjee/sdrt-vhost

MAINTAINER Matt Mukerjee "mukerjee@cs.cmu.edu"

RUN apt-get update && apt-get install -y \
                              iperf3 \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["iperf3"]
CMD ["-s"]
