FROM mukerjee/sdrt-vhost

MAINTAINER Matt Mukerjee "mukerjee@cs.cmu.edu"

RUN apt-get update && apt-get install -y \
			      flowgrind \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["flowgrindd"]
CMD ["-d"]
