FROM mukerjee/sdrt-base

MAINTAINER Matt Mukerjee "mukerjee@cs.cmu.edu"

RUN apt-get update && apt-get install -y \
                              software-properties-common
RUN add-apt-repository ppa:openjdk-r/ppa 
RUN apt-get update && apt-get install -y \
                              openjdk-7-jdk \
                              maven \			    
    && rm -rf /var/lib/apt/lists/*

ADD https://github.com/intel-hadoop/HiBench/archive/master.tar.gz /tmp/HiBench.tar.gz
WORKDIR /root
RUN tar xfz /tmp/HiBench.tar.gz && mv HiBench-master HiBench

RUN rm /tmp/*.tar.gz

CMD pipework --wait && pipework --wait -i eth2
