FROM mukerjee/sdrt-base

MAINTAINER Matt Mukerjee "mukerjee@cs.cmu.edu"

RUN apt-get update && apt-get install -y \
			      flowgrind \
    && rm -rf /var/lib/apt/lists/*

CMD pipework --wait && pipework --wait -i eth2 && flowgrindd -d
