FROM ubuntu

MAINTAINER Matt Mukerjee "mukerjee@cs.cmu.edu"

RUN apt-get update && apt-get install -y \
                              net-tools \
                              iputils-ping \
			      gcc \
			      cmake \
                              iperf3 \
    && rm -rf /var/lib/apt/lists/*

ADD https://github.com/mukerjee/sdrt/archive/master.tar.gz /tmp/sdrt.tar.gz
WORKDIR /root
RUN tar xfz /tmp/sdrt.tar.gz && mv sdrt-master sdrt
WORKDIR /root/sdrt/adu-send/lib
RUN make -j install

RUN rm /tmp/*.tar.gz

WORKDIR /root/
ENTRYPOINT ["iperf3"]
CMD ["-s"]